name: PR Verifier

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

permissions:
  checks: write # Allow access to checks to write check runs.
  checks-reason: to create and update checks #Checkout: https://github.com/kubernetes-sigs/kubebuilder-release-tools/blob/01981b8498d7b87658301e2a1b12c56b8c61067d/verify/pkg/action/plugin.go#L88
  pull-requests: read
  pull-requests-reason: to get PR title
  
jobs:
  verify:
    name: Verify PR contents
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Verifier action
        uses: ./.github/actions/verifier
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
