name: PR Verifier

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

permissions:
  checks: write # Allow access to checks to write check runs.
  
jobs:
  verify:
    name: Verify PR contents
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Verifier action
        uses: ./.github/actions/verifier
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
